name: 'i18next resources validator'
description: 'Validates localization resources for projects using i18next'
author: 'Matheus Jardim Bernardes'

branding:
  color: "green"
  icon: "check-circle"

inputs:
  resources_path:
    description: 'Path of the folder containing the json files to be evaluated'
    required: true
  quiet:
    description: 'Reduces the amount of logs printed during evaluation.'
    required: false
    default: false

runs:
  using: node20
  main: dist/index.js
